### PR TITLE
RWA-2028 Add ignore line to audit.json

### PR DESCRIPTION
**Pull request by mcareyma**
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RWA-2028

### Change description ###
This will stop the failure in the security sweep.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by rafalkalita — APPROVED** [review]
LGTM

**Comment by mcareyma** [comment]
"fingerprint":"100000_A Client Error response code was returned by the server_http://wa-task-management-api-aat.service.core-compute-aat.internal/task/task-types?jurisdiction=jurisdiction_GET","detail":"A Client Error response code was returned by the server \n Evidence: HTTP/1.1 401 \n Solution: \n Other info: \n Reference: "

**Review by mrmsali — APPROVED** [review]
Looks good to me.

**Review by mrmsali — APPROVED** [review]
Looks good to me.

**Pull request merged**
